package com.zhuxiaoming.kr36.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhuxiaoming.kr36.database.LoginBean;
import com.zhuxiaoming.kr36.database.FavoriteBean;

import com.zhuxiaoming.kr36.database.LoginBeanDao;
import com.zhuxiaoming.kr36.database.FavoriteBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginBeanDaoConfig;
    private final DaoConfig favoriteBeanDaoConfig;

    private final LoginBeanDao loginBeanDao;
    private final FavoriteBeanDao favoriteBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginBeanDaoConfig = daoConfigMap.get(LoginBeanDao.class).clone();
        loginBeanDaoConfig.initIdentityScope(type);

        favoriteBeanDaoConfig = daoConfigMap.get(FavoriteBeanDao.class).clone();
        favoriteBeanDaoConfig.initIdentityScope(type);

        loginBeanDao = new LoginBeanDao(loginBeanDaoConfig, this);
        favoriteBeanDao = new FavoriteBeanDao(favoriteBeanDaoConfig, this);

        registerDao(LoginBean.class, loginBeanDao);
        registerDao(FavoriteBean.class, favoriteBeanDao);
    }
    
    public void clear() {
        loginBeanDaoConfig.getIdentityScope().clear();
        favoriteBeanDaoConfig.getIdentityScope().clear();
    }

    public LoginBeanDao getLoginBeanDao() {
        return loginBeanDao;
    }

    public FavoriteBeanDao getFavoriteBeanDao() {
        return favoriteBeanDao;
    }

}
