package com.zhuxiaoming.kr36.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_BEAN".
 */
public class FavoriteBean {

    private Long id;
    private String feedId;
    private String imgUrl;
    private String author;
    private String title;
    private String type;
    private Long time;

    public FavoriteBean() {
    }

    public FavoriteBean(Long id) {
        this.id = id;
    }

    public FavoriteBean(Long id, String feedId, String imgUrl, String author, String title, String type, Long time) {
        this.id = id;
        this.feedId = feedId;
        this.imgUrl = imgUrl;
        this.author = author;
        this.title = title;
        this.type = type;
        this.time = time;
    }

    public FavoriteBean(String feedId, String imgUrl, String author, String title, String type, Long time) {
        this.feedId = feedId;
        this.imgUrl = imgUrl;
        this.author = author;
        this.title = title;
        this.type = type;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFeedId() {
        return feedId;
    }

    public void setFeedId(String feedId) {
        this.feedId = feedId;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
